from django.urls import path
# pyrefly: ignore [missing-import]
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('settings/', views.settings_view, name='settings'),
    path('categories/', views.categories_list, name='categories_list'),
    path('categories/edit/', views.category_edit_api, name='category_edit_api'),
    path('subcategories/edit/', views.subcategory_edit_api, name='subcategory_edit_api'),
    path('profile/', views.profile_view, name='profile'),
    path('forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('verify-otp/', views.verify_otp_view, name='verify_otp'),
    path('reset-password/', views.reset_password_view, name='reset_password'),
    path('products/', views.product_list, name='product_list'),
    path('products/add/', views.product_add, name='product_add'),
    path('products/<int:pk>/', views.product_detail, name='product_detail'),
    path('products/<int:pk>/edit/', views.product_edit, name='product_edit'),
    path('products/<int:pk>/delete/', views.product_delete, name='product_delete'),
    path('products/<int:pk>/restore/', views.product_restore, name='product_restore'),
    path('products/<int:pk>/permanent-delete/', views.product_permanent_delete, name='product_permanent_delete'),
    path('products/deleted/', views.deleted_products, name='deleted_products'),
    path('products/export/', views.export_products_csv, name='export_products_csv'),
    path('location/', views.location_view, name='location'),
    path('location/entry/<int:pk>/delete/', views.delete_inventory_entry, name='delete_inventory_entry'),
    path('location/entry/<int:pk>/edit-price/', views.edit_inventory_price, name='edit_inventory_price'),
    # ── Order Module ──
    path('orders/', views.order_list, name='order_list'),
    path('orders/new/', views.order_create, name='order_create'),
    path('orders/save/', views.order_save_api, name='order_save_api'),
    path('orders/<int:pk>/', views.order_detail_api, name='order_detail_api'),
    path('orders/<int:pk>/edit/', views.order_edit, name='order_edit'),
    path('orders/<int:pk>/delete/', views.order_delete, name='order_delete'),
    # ── Users (Admin Only) ──
    path('users/', views.users_list, name='users_list'),
    path('users/<int:user_id>/', views.user_details, name='user_details'),
    path('users/<int:user_id>/products/', views.user_products, name='user_products'),
    path('users/<int:user_id>/locations/', views.user_locations, name='user_locations'),
    path('users/<int:user_id>/orders/', views.user_orders, name='user_orders'),
    path('users/<int:user_id>/activity/', views.user_activity, name='user_activity'),
    # AJAX endpoints
    path('ajax/subcategories/', views.ajax_subcategories, name='ajax_subcategories'),
    path('ajax/products/search/', views.ajax_product_search, name='ajax_product_search'),
    path('ajax/preview-code/', views.ajax_preview_code, name='ajax_preview_code'),
    path('ajax/order/locations/', views.ajax_order_locations, name='ajax_order_locations'),
    path('settings/migrate-codes/', views.migrate_product_codes, name='migrate_product_codes'),
    path('api/products/search/', views.api_product_search, name='api_product_search'),
    path('wishlist/', views.wishlist_list, name='wishlist_list'),
    path('wishlist/toggle/<int:product_id>/', views.wishlist_toggle, name='wishlist_toggle'),
    path('register/', views.register_view, name='register'),
    # ── User Approval Management (Admin Only) ──
    path('approval-requests/', views.approval_requests, name='approval_requests'),
    path('approval-requests/approve/<int:user_id>/', views.approve_user_api, name='approve_user_api'),
    path('approval-requests/reject/<int:user_id>/', views.reject_user_api, name='reject_user_api'),
    path('approval-requests/bulk-approve/', views.bulk_approve_api, name='bulk_approve_api'),
    path('approval-requests/bulk-reject/', views.bulk_reject_api, name='bulk_reject_api'),
    path('approval-requests/history/', views.approval_history_api, name='approval_history_api'),
    # ── Admin Control Center ──
    path('admin-control/', views.admin_control_center, name='admin_control'),
    path('admin-control/users/', views.admin_users, name='admin_users'),
    path('admin-control/users/<int:user_id>/', views.admin_user_detail, name='admin_user_detail'),
    path('admin-control/audit-logs/', views.admin_audit_logs, name='admin_audit_logs'),
    path('admin-control/users/<int:user_id>/activity/', views.admin_user_activity_api, name='admin_user_activity_api'),
]