services:
  - type: web
    name: wms-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app.wsgi:application"
    disk:
      name: wms-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: app.settings
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: EMAIL_HOST_USER
        value: support.productpilotgo@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: "yxcv anyd dinq bzst"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_PORT
        value: "587"
      - key: DEFAULT_FROM_EMAIL
        value: support.productpilotgo@gmail.com
      - key: DATABASE_URL
        fromDatabase:
          name: wms-db
          property: connectionString

databases:
  - name: wms-db
    plan: free
