# Generated by Django 4.2.16 on 2026-05-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCodeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, verbose_name="Enable Auto Product Code"
                    ),
                ),
                (
                    "prefix_format",
                    models.CharField(
                        default="{YEAR}{MONTH}{SEQ}",
                        help_text="Template: {YEAR}, {MONTH}, {SEQ}",
                        max_length=100,
                    ),
                ),
                ("sequence_length", models.PositiveIntegerField(default=4)),
                (
                    "reset_monthly",
                    models.BooleanField(
                        default=True, verbose_name="Reset Sequence Monthly"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Code Settings",
                "verbose_name_plural": "Product Code Settings",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="ProductCodeSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.CharField(max_length=3)),
                ("last_sequence", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Product Code Sequence",
                "unique_together": {("year", "month")},
            },
        ),
    ]
