# Generated by Django 4.2.16 on 2026-05-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aps", "0002_productcodesettings_product_product_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Comma-separated tags", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
