# Generated by Django 4.2.16 on 2026-05-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aps", "0003_product_description_product_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sh_code",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="warehouseinventory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="warehouseinventory",
            name="location_number",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_name", "is_deleted"], name="idx_product_name_active"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_deleted"], name="idx_product_cat_active"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_deleted", "-created_at"], name="idx_product_active_date"
            ),
        ),
    ]
