# Generated by Django 4.2.16 on 2026-05-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aps", "0004_product_deleted_at_product_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_code",
        ),
        migrations.AlterField(
            model_name="product",
            name="asin_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
    ]
