# Generated by Django 4.2.16 on 2026-06-09 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("aps", "0008_add_approval_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="warehouseinventory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="warehouseinventory",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_export",
                    models.BooleanField(
                        default=False, help_text="Allow exporting company-wide data."
                    ),
                ),
                (
                    "can_manage_all_orders",
                    models.BooleanField(
                        default=False,
                        help_text="View and manage orders created by other users.",
                    ),
                ),
                (
                    "can_manage_settings",
                    models.BooleanField(
                        default=False,
                        help_text="Access system settings and product code configuration.",
                    ),
                ),
                (
                    "can_delete_products",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete, restore, and permanently delete products.",
                    ),
                ),
                (
                    "can_delete_inventory",
                    models.BooleanField(
                        default=False, help_text="Delete warehouse inventory entries."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("user_approved", "User Approved"),
                            ("user_rejected", "User Rejected"),
                            ("user_deactivated", "User Deactivated"),
                            ("user_activated", "User Activated"),
                            ("product_created", "Product Created"),
                            ("product_updated", "Product Updated"),
                            ("product_deleted", "Product Deleted"),
                            ("product_restored", "Product Restored"),
                            ("product_permanent_delete", "Product Permanently Deleted"),
                            ("inventory_created", "Inventory Created"),
                            ("inventory_updated", "Inventory Updated"),
                            ("inventory_deleted", "Inventory Deleted"),
                            ("location_changed", "Location Changed"),
                            ("order_created", "Order Created"),
                            ("order_updated", "Order Updated"),
                            ("order_deleted", "Order Deleted"),
                            ("export", "Data Export"),
                            ("settings_changed", "Settings Changed"),
                            ("category_created", "Category Created"),
                            ("subcategory_created", "Subcategory Created"),
                            ("wishlist_add", "Wishlist Add"),
                            ("wishlist_remove", "Wishlist Remove"),
                            ("permission_changed", "Permission Changed"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                (
                    "details",
                    models.TextField(
                        blank=True, help_text="JSON or text details of the change."
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"], name="idx_audit_action_date"
                    ),
                    models.Index(
                        fields=["user", "-created_at"], name="idx_audit_user_date"
                    ),
                    models.Index(
                        fields=["object_type", "object_id"], name="idx_audit_object"
                    ),
                ],
            },
        ),
    ]
