# Generated by Django 4.2.16 on 2026-06-10 07:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("aps", "0011_per_user_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="asin_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("asin_code", "created_by")},
        ),
    ]
