# Generated by Django 4.2.16 on 2026-06-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aps", "0012_product_code_unique_per_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="exchange_value",
            field=models.DecimalField(
                decimal_places=4, default=1, max_digits=12, verbose_name="Value"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="rmb",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="RMB"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="rupees",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=14, verbose_name="Rupees"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country_code",
            field=models.CharField(default="+91", max_length=5),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mobile_number",
            field=models.CharField(blank=True, db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("user_approved", "User Approved"),
                    ("user_rejected", "User Rejected"),
                    ("user_deactivated", "User Deactivated"),
                    ("user_activated", "User Activated"),
                    ("product_created", "Product Created"),
                    ("product_updated", "Product Updated"),
                    ("product_deleted", "Product Deleted"),
                    ("product_restored", "Product Restored"),
                    ("product_permanent_delete", "Product Permanently Deleted"),
                    ("inventory_created", "Inventory Created"),
                    ("inventory_updated", "Inventory Updated"),
                    ("inventory_deleted", "Inventory Deleted"),
                    ("location_changed", "Location Changed"),
                    ("order_created", "Order Created"),
                    ("order_updated", "Order Updated"),
                    ("order_deleted", "Order Deleted"),
                    ("export", "Data Export"),
                    ("settings_changed", "Settings Changed"),
                    ("category_created", "Category Created"),
                    ("subcategory_created", "Subcategory Created"),
                    ("wishlist_add", "Wishlist Add"),
                    ("wishlist_remove", "Wishlist Remove"),
                    ("permission_changed", "Permission Changed"),
                    ("email_sent", "Email Sent"),
                    ("email_failed", "Email Failed"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
