# Generated by Django 6.0.6 on 2026-06-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aps", "0014_passwordresetotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcodesettings",
            name="prefix_format",
            field=models.CharField(
                default="{YEAR}{MONTH}{SEQ}",
                help_text="Template: {YEAR}, {MONTH}, {DATE}, {SEQ}",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="can_manage_settings",
            field=models.BooleanField(
                default=True,
                help_text="Access system settings and product code configuration.",
            ),
        ),
    ]
