# Generated by Django 4.2.16 on 2026-06-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aps', '0015_alter_productcodesettings_prefix_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('user_approved', 'User Approved'), ('user_rejected', 'User Rejected'), ('user_deactivated', 'User Deactivated'), ('user_activated', 'User Activated'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('product_restored', 'Product Restored'), ('product_permanent_delete', 'Product Permanently Deleted'), ('inventory_created', 'Inventory Created'), ('inventory_updated', 'Inventory Updated'), ('inventory_deleted', 'Inventory Deleted'), ('location_changed', 'Location Changed'), ('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_deleted', 'Order Deleted'), ('export', 'Data Export'), ('settings_changed', 'Settings Changed'), ('category_created', 'Category Created'), ('category_updated', 'Category Updated'), ('subcategory_created', 'Subcategory Created'), ('subcategory_updated', 'Subcategory Updated'), ('wishlist_add', 'Wishlist Add'), ('wishlist_remove', 'Wishlist Remove'), ('permission_changed', 'Permission Changed'), ('email_sent', 'Email Sent'), ('email_failed', 'Email Failed')], db_index=True, max_length=40),
        ),
    ]
